version: "3"

services:
    mongodb:
        container_name: mongodb
        image: mongo
        volumes:
          - ./database:/data/db
        ports:
          - 27017:27017

    app:
        depends_on: 
            - mongodb
        build: 
            dockerfile: Dockerfile.dev
            context: ./
        container_name: "jarvis"
        volumes: 
            - ./session:/session
            - ./:/app
        environment:
            WEBSOCKET_PORT: 8000
            DATABASE_URL: "mongodb://mongodb:27017/jarvis"
            TOKEN_SECRET: "mysupersecretkey"
            CHOKIDAR_USEPOLLING: "true"
        expose:
            - "8000"
        working_dir: /app
        command: bash -c "npm install && npm run dev"
