version: "3"

services:
    mongodb:
        container_name: mongodb
        image: mongo
        volumes:
          - ./database:/data/db
        ports:
          - 27017:27017
        restart: always

    app:
        depends_on: 
            - mongodb
        build: ./
        container_name: "jarvis"
        volumes: 
            - ./session:/session
        working_dir: /app
        environment:
            WEBSOCKET_PORT: 8000
            DATABASE_URL: "mongodb://mongodb:27017/jarvis"
            TOKEN_SECRET: "mysupersecretkey"
        expose:
            - "8000"
        restart: always
