enum events {
  WHATSAPP_SEND = "WHATSAPP_SEND",
  WHATSAPP_RESPONSE = "WHATSAPP_RESPONSE",
  WHATSAPP_SEND_IMAGE_AS_STICKER = "WHATSAPP_SEND_IMAGE_AS_STICKER",
  WHATSAPP_SEND_URL_AS_STICKER = "WHATSAPP_SEND_URL_AS_STICKER",
}

export default events;
