enum events {
  SEND_STATUS = "SEND_STATUS",
  PLAYER_QUERY_ADDED = "PLAYER_QUERY_ADDED",
  PLAYER_EMPTY_PLAYLIST = "PLAYER_EMPTY_PLAYLIST",
  PLAYER_PLAY = "PLAYER_PLAY",
  PLAYER_PAUSE = "PLAYER_PAUSE",
}

export default events;
