import { ServiceFetcherDTO } from "../services/QueryFetcher/ServiceFetcher";

enum events {
  EMIT_STATUS = "EMIT_STATUS",
  EMIT_PLAYER_QUERY_ADDED = "EMIT_PLAYER_QUERY_ADDED",
  EMIT_PLAYER_EMPTY_PLAYLIST = "EMIT_PLAYER_EMPTY_PLAYLIST",
  EMIT_PLAYER_PLAY = "EMIT_PLAYER_PLAY",
  EMIT_PLAYER_PAUSE = "EMIT_PLAYER_PAUSE",
  EMIT_PLAYER_CLEAR = "EMIT_PLAYER_CLEAR",
  EMIT_PLAYER_STOP = "EMIT_PLAYER_STOP",
  EMIT_PLAYER_APPEND = "EMIT_PLAYER_APPEND",
  EMIT_PLAYER_NEXT = "EMIT_PLAYER_NEXT",
  EMIT_PLAYER_PREVIOUS = "EMIT_PLAYER_PREVIOUS",
  EMIT_PLAYER_EMPTY = "EMIT_PLAYER_EMPTY",
  EMIT_PLAYER_PLAYLIST = "EMIT_PLAYER_PLAYLIST",
  EMIT_PLAYER_GOTO = "EMIT_PLAYER_GOTO",

  EMIT_PLAYER_OUT_OF_BOUNDS = "EMIT_PLAYER_OUT_OF_BOUNDS",
  EMIT_PLAYER_PLAYLIST_END = "EMIT_PLAYER_PLAYLIST_END",
}

export default events;
