enum events {
  REQUEST_STATUS = "REQUEST_STATUS",
  REQUEST_PLAYER_QUERY_ADDED = "REQUEST_PLAYER_QUERY_ADDED",
  REQUEST_PLAYER_EMPTY_PLAYLIST = "REQUEST_PLAYER_EMPTY_PLAYLIST",
  REQUEST_PLAYER_PLAY = "REQUEST_PLAYER_PLAY",
  REQUEST_PLAYER_STOP = "REQUEST_PLAYER_STOP",
  REQUEST_PLAYER_CLEAR = "REQUEST_PLAYER_CLEAR",
  REQUEST_PLAYER_PAUSE = "REQUEST_PLAYER_PAUSE",
  REQUEST_PLAYER_APPEND = "REQUEST_PLAYER_APPEND",
  REQUEST_PLAYER_NEXT = "REQUEST_PLAYER_NEXT",
  REQUEST_PLAYER_PREVIOUS = "REQUEST_PLAYER_PREVIOUS",
  REQUEST_PLAYER_PLAYLIST = "REQUEST_PLAYER_PLAYLIST",
  REQUEST_PLAYER_GOTO = "REQUEST_PLAYER_GOTO",
}

export default events;
